AppBundle\Entity\Panier:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PanierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        quantite:
            type: integer
            column: Quantite
        prix:
            type: integer
            column: Prix
        tVA:
            type: integer
            column: TVA
    lifecycleCallbacks: {  }
